### ISSUE TITLE
loop detected when installing 10_BETA/i386

### ISSUE THREAD

**Issue by bsiegert** [gson1703/anita#14]
I just installed anita 2.10 from pkgsrc (on macOS, FWIW) and ran

```
anita interact http://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-10/202310140930Z/i386/
```

During the installation, I get a "RuntimeError: loop detected", see the screenshot. 

<img width="666" alt="Bildschirmfoto 2023-10-16 um 10 15 11" src="https://github.com/gson1703/anita/assets/866330/9157cdde-0071-46ff-b490-583d977e6b40">

I suspect this may be due to the gpufw set?

**Comment by bsiegert** [comment]
The same happens with amd64. From what I can tell, it does not find the kern-GENERIC set.

Maybe this is actually a problem with the installation CD that anita builds. AIUI, it uses `hdiutil` on macOS. It looks like the CD does not contain Rockridge extensions maybe? The file names look like

```
% ls /Volumes/DOWNLOAD/AMD64/BINARY/SETS
BASETAR.XZ		ETCTAR.XZ		KERN-GENERICTAR.XZ	MODULESTAR.XZ		TESTSTAR.XZ
BASETGZ.MISSING		ETCTGZ.MISSING		KERN-GENERICTGZ.MISSING	MODULESTGZ.MISSING	TESTSTGZ.MISSING
COMPTAR.XZ		GPUFWTAR.XZ		MISCTAR.XZ		RESCUETAR.XZ
COMPTGZ.MISSING		GPUFWTGZ.MISSING	MISCTGZ.MISSING		RESCUETGZ.MISSING
```

**Comment by gson1703** [comment]
I'm no longer using pkgsrc on macOS, but I tried to reproduce the issue on a mac where python, qemu, etc, are installed using Homebrew.

For me, i386 worked, and amd64 failed differently from what you described.  It didn't even get to sysinst, but failed while booting the install CD, with the message

```
NetBSD/x86 cd9660 Primary Bootstrap
Can't read CD
```

To start with the i386 case, can you try ```anita --memory-size 128M --structured-log-file i386.slog install http://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-10/202310140930Z/i386/``` and if that fails, attach the i386.slog file?

**Comment by bsiegert** [comment]
Thanks for the quick answer!

The two things I saw were indeed two different issues.

- For amd64, the CD is missing RockRidge extensions. Joliet works too, so add that -- I sent you #15.
- For i386, the gpufw set was not downloaded for some reason, and retrying fixed it.
